version: "3.7"
services:
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - database:database
    restart: "no"
  download:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    ports:
      - 8888:80
    volumes:
      - ../download-service/:/app/
    restart: "no"
  dev-migrations:
    volumes:
      - ./config/dev-migrations:/data/migrations
