version: '3.7'
services:
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    privileged: true
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - database:database
    restart: "no"    