PREFIX adres: <https://data.vlaanderen.be/ns/adres#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/be278471a2a318edba32e7ac4294c0eafbe4c8077a34dcbb9c2e43211d4a78a6> {
    <https://data.vlaanderen.be/id/postinfo/2800> adres:postnaam "Walem" .
    <https://data.vlaanderen.be/id/postinfo/2811> adres:postnaam "Hombeek" .
    <https://data.vlaanderen.be/id/postinfo/2811> adres:postnaam "Leest" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/be278471a2a318edba32e7ac4294c0eafbe4c8077a34dcbb9c2e43211d4a78a6> {
    <https://data.vlaanderen.be/id/postinfo/2811> adres:postnaam "Mechelen" .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/be278471a2a318edba32e7ac4294c0eafbe4c8077a34dcbb9c2e43211d4a78a6> {
    ?postInfo a adres:Postinfo .
  }
}
