PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/c84963304e7954547b0ad6b2020764fa> foaf:familyName "Zwijndrecht-edit" .
    <http://data.lblod.info/id/bestuurseenheden/c362abc58ac4579ff417824ce620962ac57bc344b34fe8f51d21b35ef54da36d> skos:prefLabel "Zwijndrecht-edit" .

  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/c84963304e7954547b0ad6b2020764fa> foaf:familyName "Zwijndrecht" .
    <http://data.lblod.info/id/bestuurseenheden/c362abc58ac4579ff417824ce620962ac57bc344b34fe8f51d21b35ef54da36d> skos:prefLabel "Zwijndrecht" .

  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/c84963304e7954547b0ad6b2020764fa> foaf:familyName "Zwijndrecht-edit" .
    <http://data.lblod.info/id/bestuurseenheden/c362abc58ac4579ff417824ce620962ac57bc344b34fe8f51d21b35ef54da36d> skos:prefLabel "Zwijndrecht-edit" .
  }
}
