DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/organizations>
  }
  VALUES ?s {
    <https://data.vlaanderen.be/ns/63102ef8-4bff-5bb2-9f44-92584b93088e>
    <https://data.vlaanderen.be/ns/f750732f-c4f6-5639-b8a4-a777b394a436>
    <https://data.vlaanderen.be/ns/6f7d9a92-38ea-5826-9dbd-4908ec6ac7cc>
    <https://data.vlaanderen.be/ns/fa1367b3-e7ea-504f-8dda-d7cf65a320b8>
    <https://data.vlaanderen.be/ns/56a6f851-51a2-5608-a86e-8580bcc477dd>
    <https://data.vlaanderen.be/ns/61d77aa5-cef7-58d4-8d8b-18eb00f4ab28>
    <https://data.vlaanderen.be/ns/543c961e-6d79-58b9-bf1b-924b835bd360>
    <https://data.vlaanderen.be/ns/471cb8e5-246a-580e-9c0b-8c24c1ac35d2>
    <https://data.vlaanderen.be/ns/10216d17-e237-5067-9104-b61b88fe17d8>
    <https://data.vlaanderen.be/ns/c3a86367-133f-50b2-a769-d9ef8f96324f>
    <https://data.vlaanderen.be/ns/049b625c-5341-5147-aaaf-267eb5f01117>
    <https://data.vlaanderen.be/ns/f61efe4c-4aac-5c7a-b8de-826dc482c64a>
    <https://data.vlaanderen.be/ns/b463887c-c322-552d-8267-63f38280c733>
    <https://data.vlaanderen.be/ns/c6e502a4-f5f8-5c93-be72-579413a8952b>
    <http://data.lblod.info/id/adressen/1d100e46-c962-57c6-9726-aa5de2a4987f>
    <http://data.lblod.info/id/adressen/248b5dfa-a7cc-5fdd-a09a-0d9b582c427a>
    <http://data.lblod.info/id/adressen/305ebfba-fd6b-5d62-84b5-04366659d5ba>
    <http://data.lblod.info/id/adressen/39b9a238-9242-5c76-a7c4-5b7b669c9e94>
    <http://data.lblod.info/id/adressen/42535a33-9e2e-5c99-8846-ae5b19b429bb>
    <http://data.lblod.info/id/adressen/42e57b69-5b63-5e96-bc4d-562a499eb7e7>
    <http://data.lblod.info/id/adressen/5d72da22-12bc-5827-9630-94fb544435bf>
    <http://data.lblod.info/id/adressen/6a77eeac-185f-57ad-b62a-48df7d174f37>
    <http://data.lblod.info/id/adressen/7d8eac75-610d-5f82-848c-1d38344161ca>
    <http://data.lblod.info/id/adressen/7c7b2255-4b08-56f7-b086-1b9cc589527c>
    <http://data.lblod.info/id/adressen/88ffdaf0-ec83-5bd7-a65b-f893d394f389>
    <http://data.lblod.info/id/adressen/a155480a-409c-5bf0-876f-3957090512d6>
    <http://data.lblod.info/id/adressen/a668c20e-ebc2-5ba0-9ded-df6e0e326c23>
    <http://data.lblod.info/id/adressen/a9cad220-4b94-5cc6-bdfc-a97bcbafb3b5>
    <http://data.lblod.info/id/adressen/b04d952e-2e8f-52ca-8937-cae283aac25d>
    <http://data.lblod.info/id/adressen/b503c200-5347-5d01-884d-e5697225ae89>
    <http://data.lblod.info/id/adressen/b63d697a-f03a-532c-bdf6-efc0657d3c15>
    <http://data.lblod.info/id/adressen/b72047de-6224-5fbe-8acf-08b59ceb82bf>
    <http://data.lblod.info/id/adressen/b7c12049-fee0-55c4-931b-04130c290bf1>
    <http://data.lblod.info/id/adressen/c3926d2e-98bc-5727-800b-91172e2bf9e8>
    <http://data.lblod.info/id/adressen/cabf8023-64ee-5c74-a16c-926ceb5c0635>
    <http://data.lblod.info/id/adressen/d51c9ca0-f406-550e-8f3f-8eb6a18e9d71>
    <http://data.lblod.info/id/adressen/d44d87aa-85c1-5433-b754-1523c27b63f8>
    <http://data.lblod.info/id/adressen/d5a720d6-4a90-5400-b6b8-ccb68dc2090d>
    <http://data.lblod.info/id/adressen/e4410385-2e66-5807-8bfe-bd5cf2455111>
    <http://data.lblod.info/id/adressen/f14d72fa-6b74-58c9-8696-0a979b91e08e>
    <http://data.lblod.info/id/adressen/f4ecd07e-9f8a-5f37-b307-3ebb039ad8e2>
    <http://data.lblod.info/id/adressen/f970edab-ede3-5bfc-9fe4-4bd78a576994>
    <http://data.lblod.info/id/contact-punten/0ec507a8-782c-5fa8-86b8-9274843d77f7>
    <http://data.lblod.info/id/contact-punten/0ec1c3fa-9477-5d87-b684-632b744693ca>
    <http://data.lblod.info/id/contact-punten/172afd71-d7a0-5233-800f-ba53104119ae>
    <http://data.lblod.info/id/contact-punten/1d865089-ff71-58df-a707-1ef22ac0c4dd>
    <http://data.lblod.info/id/contact-punten/28a1434e-a33a-5c0e-9a96-a31c21889017>
    <http://data.lblod.info/id/contact-punten/34a47c34-e60a-558f-b436-82dc39096beb>
    <http://data.lblod.info/id/contact-punten/447d054d-24d5-5879-b3ed-719d15efce2c>
    <http://data.lblod.info/id/contact-punten/46b92672-1c5a-5937-8025-981ca65f737e>
    <http://data.lblod.info/id/contact-punten/57854b8e-24c8-58c0-ad18-94d727555cfa>
    <http://data.lblod.info/id/contact-punten/5dc76748-25ef-571b-9e1d-f27bb24298d0>
    <http://data.lblod.info/id/contact-punten/69863e4c-69be-5186-9647-0232f2149c5f>
    <http://data.lblod.info/id/contact-punten/67da392b-731a-5062-ac01-878a66a77d2f>
    <http://data.lblod.info/id/contact-punten/780e2702-c72c-5e7d-ac98-cf7155b898d0>
    <http://data.lblod.info/id/contact-punten/827c55d2-a803-52e7-a774-0601cd31719e>
    <http://data.lblod.info/id/contact-punten/8226864f-2f63-530b-af04-07d14be28bce>
    <http://data.lblod.info/id/contact-punten/87a3359d-2a74-5302-b0b4-cad1e22d582b>
    <http://data.lblod.info/id/contact-punten/8ce806a9-991b-579c-963f-3e41025ec3f4>
    <http://data.lblod.info/id/contact-punten/94c59d09-206a-52c4-8109-1c6b28a05b35>
    <http://data.lblod.info/id/contact-punten/a1ed3df3-2d80-585d-9560-1de0f6bd4ce1>
    <http://data.lblod.info/id/contact-punten/a93ad3bd-0265-5c97-bd86-b038e6297ac8>
    <http://data.lblod.info/id/contact-punten/b289b3d0-4013-59df-8ff0-c082f98edff2>
    <http://data.lblod.info/id/contact-punten/b43b3aa6-6812-5375-b9cd-90c8f962a7ba>
    <http://data.lblod.info/id/contact-punten/b57d03cf-e097-586b-8de4-f0d531271e32>
    <http://data.lblod.info/id/contact-punten/b9d5ca5b-e165-5cf9-a3f0-b19acc802b92>
    <http://data.lblod.info/id/contact-punten/bb9fc6fd-556d-54f4-a76b-d326d4f952e5>
    <http://data.lblod.info/id/contact-punten/bf32058f-1d4a-573c-9575-580c8e5c9be0>
    <http://data.lblod.info/id/contact-punten/d86d53a1-ecb4-50f0-a49b-91f09a75ef6e>
    <http://data.lblod.info/id/contact-punten/dff89a2c-063f-5ff0-a0c0-0afbf3c4aa86>
    <http://data.lblod.info/id/contact-punten/e1ebc94d-cdbd-5049-865e-3dccea5d230b>
    <http://data.lblod.info/id/contact-punten/e83f8aa8-4236-5391-8cc1-a5bee4987dcf>
    <http://data.lblod.info/id/contact-punten/ea7d9249-f41f-5755-a11c-5fcf204d9daa>
    <http://data.lblod.info/id/contact-punten/eb7d8a51-0de5-5759-bfe4-5f69e3ce6e96>
    <http://data.lblod.info/id/contact-punten/ef4cece9-4df9-5e7c-b92c-d6b6abb77c5d>
    <http://data.lblod.info/id/contact-punten/f11f39e5-4a21-56e9-bdbd-5be6951fbe4c>
    <http://data.lblod.info/id/contact-punten/f67486ef-74c7-5ae9-b9e7-a60da86161ad>
    <http://data.lblod.info/id/gestructureerdeIdentificator/23512988-47f3-5867-99cd-42cdde22aef2>
    <http://data.lblod.info/id/gestructureerdeIdentificator/3e901f15-d04d-533d-9eb4-c1377f8e58a1>
    <http://data.lblod.info/id/gestructureerdeIdentificator/45d618c3-6c34-5e3d-8393-bc7494a859ad>
    <http://data.lblod.info/id/gestructureerdeIdentificator/4de68d59-38ba-5e22-ac51-e0fc3143e455>
    <http://data.lblod.info/id/gestructureerdeIdentificator/56e75417-7aee-5fe2-a0f3-5cb43a32b26c>
    <http://data.lblod.info/id/gestructureerdeIdentificator/57345176-ba12-5272-943a-875a0bfd91a7>
    <http://data.lblod.info/id/gestructureerdeIdentificator/5eb366e6-4df5-595b-8c9b-fd3b265f777d>
    <http://data.lblod.info/id/gestructureerdeIdentificator/8471488b-c729-5076-aab9-4bc6b9122331>
    <http://data.lblod.info/id/gestructureerdeIdentificator/91b02459-4eb1-50fb-9084-05c9cacd76ec>
    <http://data.lblod.info/id/gestructureerdeIdentificator/99b690c1-cb6f-5ec9-a109-d4eb12368ad0>
    <http://data.lblod.info/id/gestructureerdeIdentificator/b218f489-f882-5b32-9341-da02cde75360>
    <http://data.lblod.info/id/gestructureerdeIdentificator/af6399e3-52a1-5b7f-ad46-c7ca63a7640e>
    <http://data.lblod.info/id/gestructureerdeIdentificator/bbc2f431-913a-5f50-8778-f0e6bdadf711>
    <http://data.lblod.info/id/gestructureerdeIdentificator/baa3f516-0818-543e-a593-3bb9fceab795>
    <http://data.lblod.info/id/gestructureerdeIdentificator/b86677c7-6ebf-5e8e-822c-ebdd479cb857>
    <http://data.lblod.info/id/gestructureerdeIdentificator/bd1df6e0-46ec-53b4-bb15-d736d13ace48>
    <http://data.lblod.info/id/gestructureerdeIdentificator/c00f3d12-5b65-5c5b-b95b-55467529979f>
    <http://data.lblod.info/id/gestructureerdeIdentificator/c4e8c730-172f-52b6-af0b-4578d7c6d686>
    <http://data.lblod.info/id/gestructureerdeIdentificator/c3a27776-9ff8-5155-b7b1-ffd2d9861db0>
    <http://data.lblod.info/id/gestructureerdeIdentificator/c888b73e-4e11-5d9f-b6b7-ac81f04db1e0>
    <http://data.lblod.info/id/gestructureerdeIdentificator/c81d3ed2-31f9-58bc-b77f-3f65073e857d>
    <http://data.lblod.info/id/gestructureerdeIdentificator/d4246f45-fd7e-5c73-8bb4-640503602831>
    <http://data.lblod.info/id/gestructureerdeIdentificator/e94c48f2-1f32-5e5d-82d8-00ada8aa25f2>
    <http://data.lblod.info/id/gestructureerdeIdentificator/f1f889fe-5437-5ce0-8092-f594f687a675>
    <http://data.lblod.info/id/gestructureerdeIdentificator/f8f4f411-720e-5ae4-b9c6-6a4571140783>
    <http://data.lblod.info/id/identificatoren/1b5788fd-8d19-5d93-b9ff-8d77fcaf8494>
    <http://data.lblod.info/id/identificatoren/22989631-0b00-52a6-ade7-7547dec6035d>
    <http://data.lblod.info/id/identificatoren/25e8a7e9-af19-547d-83bf-549f3208702a>
    <http://data.lblod.info/id/identificatoren/3170e787-ac61-5679-9667-8b9d42c1543c>
    <http://data.lblod.info/id/identificatoren/4294160b-3892-5bd5-9fe6-153b7ae627f9>
    <http://data.lblod.info/id/identificatoren/41b6e2ac-27b6-50e9-b99c-4359ee7e1edf>
    <http://data.lblod.info/id/identificatoren/47cc71cf-3f0f-540e-ad9c-f05d8f9d3965>
    <http://data.lblod.info/id/identificatoren/4af1d00b-e67b-5dff-8847-7544f385cb1d>
    <http://data.lblod.info/id/identificatoren/5ef80c22-3105-50f5-85fe-55c57c1dea06>
    <http://data.lblod.info/id/identificatoren/75c20a4d-4ca4-5439-a302-d4173824f2e5>
    <http://data.lblod.info/id/identificatoren/77aa6017-8df2-5986-a4d1-f174ce3ef2bb>
    <http://data.lblod.info/id/identificatoren/89a199ca-822e-5da9-8cc1-7e9fa070f73e>
    <http://data.lblod.info/id/identificatoren/8b975683-e652-5542-b731-aac58289d653>
    <http://data.lblod.info/id/identificatoren/973ffcd1-5389-56d3-bd8d-fe98e23a1aca>
    <http://data.lblod.info/id/identificatoren/9cea1a8e-a83e-5452-9218-1a8bab27d470>
    <http://data.lblod.info/id/identificatoren/a6d8f4bf-d009-5fff-b5a8-ab368a6a6001>
    <http://data.lblod.info/id/identificatoren/b05d5784-650b-5118-9f39-696ee6cb72cf>
    <http://data.lblod.info/id/identificatoren/b347ba46-6d6d-52d8-b92b-8f48dc9e0865>
    <http://data.lblod.info/id/identificatoren/c19229a3-ae95-55ea-81a7-e2e8213bf305>
    <http://data.lblod.info/id/identificatoren/cba19fe9-a8c3-5ae7-ba30-52fe63ab0862>
    <http://data.lblod.info/id/identificatoren/cc8fa488-eb33-526a-9147-44d98069b4e3>
    <http://data.lblod.info/id/identificatoren/d54c0bff-d119-53b6-8147-db58b355cc9c>
    <http://data.lblod.info/id/identificatoren/e4114a02-69b2-56b3-8d03-db8d7fe391bd>
    <http://data.lblod.info/id/identificatoren/e80a8aa9-0d29-5c60-900d-43ebb72b2839>
    <http://data.lblod.info/id/identificatoren/ee811f18-1b4f-5b23-8e36-008dbc949dc2>
    <http://data.lblod.info/id/identificatoren/fa2467ab-eec5-5b71-af8d-e5587539ca4a>
    <http://www.w3.org/ns/person#79959e54-964c-534f-9d60-76e078732471>
    <http://data.lblod.info/id/lidmaatschap/1ac982a5-bebe-5584-9e92-e0c089909883>
    <http://www.w3.org/ns/person#7bb93c0f-129d-531d-9c9e-263d6f56715d>
    <http://data.lblod.info/id/lidmaatschap/24e50adc-89f9-55db-9c73-4b156ab925d4>
    <http://data.lblod.info/id/vestigingen/0129bf4c-97c6-5109-9bb6-9a323ce75c41>
    <http://data.lblod.info/id/vestigingen/12f70923-dc7b-5e5b-86e6-133a48e313c4>
    <http://data.lblod.info/id/vestigingen/1cb27faa-e87d-5838-b0e3-56f3db5c6632>
    <http://data.lblod.info/id/vestigingen/209e30bc-2923-5b09-9c17-8b96e3210d1f>
    <http://data.lblod.info/id/vestigingen/3a5929d3-431a-50d1-9452-82859866bebf>
    <http://data.lblod.info/id/vestigingen/3f98996c-7e43-5928-b4f2-99caeb6eb680>
    <http://data.lblod.info/id/vestigingen/476afeef-13f1-5238-851c-b11a278bd722>
    <http://data.lblod.info/id/vestigingen/569c0ea1-ca5b-515f-bf73-7bc9d42f191b>
    <http://data.lblod.info/id/vestigingen/56666e92-6a28-5779-b9cb-09a6a9e63339>
    <http://data.lblod.info/id/vestigingen/5c380ca7-e65c-5f3d-a0dd-7d55733e2430>
    <http://data.lblod.info/id/vestigingen/66516f20-289a-58e7-bf8e-537171f5447b>
    <http://data.lblod.info/id/vestigingen/6c1e9f18-00f2-58c7-a271-dbc0e2542606>
    <http://data.lblod.info/id/vestigingen/7922285e-5129-56ec-be49-907089b1facf>
    <http://data.lblod.info/id/vestigingen/7a6449b1-0b4e-5841-841a-db685e67b24b>
    <http://data.lblod.info/id/vestigingen/7fb0cbee-7715-5f98-9307-93aaa73fd60f>
    <http://data.lblod.info/id/vestigingen/851e69bc-57ac-5276-87db-6d71cfba85ab>
    <http://data.lblod.info/id/vestigingen/8a258fe7-1c6f-5972-b9bd-4875956ccf05>
    <http://data.lblod.info/id/vestigingen/91f48d92-c406-5995-8cb5-b4ca64c0d900>
    <http://data.lblod.info/id/vestigingen/94cf21e6-8715-5da8-828f-4a2a16652c27>
    <http://data.lblod.info/id/vestigingen/a101bc2c-7bcf-52ff-9aec-d0e4da3da0b5>
    <http://data.lblod.info/id/vestigingen/acff826c-8a1a-5a46-b170-6f3e2e88ef2e>
    <http://data.lblod.info/id/vestigingen/b9b41b79-c841-52bd-9c42-559ee7da5e3f>
    <http://data.lblod.info/id/vestigingen/b9a2267a-539c-59df-8c79-c5c51ec4c43d>
    <http://data.lblod.info/id/vestigingen/c16b9ea7-62a8-5365-9f6f-548a494b14ba>
    <http://data.lblod.info/id/vestigingen/c8c6fc4e-c9c5-5cb5-9d48-d023afc2b871>
    <http://data.lblod.info/id/vestigingen/dcfed25c-5d33-5851-90b9-497850629260>
    <http://data.lblod.info/id/vestigingen/e05c67fb-55a7-5dc5-b29b-e2003f0a6cb7>
    <http://data.lblod.info/id/vestigingen/e314b181-adaf-5f01-bdff-1f6bf09fb3a3>
    <http://data.lblod.info/id/vestigingen/f19580db-c904-55f2-a0ef-0bd75fa3dcd6>
  }

  GRAPH ?g {
    ?s ?p ?o
  }
}